# Generated by Django 2.2.10 on 2021-09-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210920_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
        migrations.AddField(
            model_name='choice',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
